# Generated by Django 2.1.1 on 2019-10-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abonos_apartado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_venta_id', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=99999, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('abono', models.IntegerField(blank=True, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99999999)),
                ('apellido', models.CharField(blank=True, max_length=99999999, null=True)),
                ('direccion', models.CharField(max_length=99999999)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=99999999, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='control_almacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo_id', models.CharField(max_length=99999999)),
                ('nombre', models.CharField(max_length=99999999)),
                ('movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Traspaso', 'Traspaso'), ('Salida', 'Salida')], max_length=99999999, null=True)),
                ('no_piezas', models.IntegerField()),
                ('registro', models.CharField(blank=True, max_length=99999999)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='control_venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Abierta', 'Abierta'), ('Pendiente', 'Pendiente'), ('Apartado', 'Apartado'), ('Cancelada', 'Cancelada'), ('Cerrada', 'Cerrada'), ('Concesion', 'Concesion'), ('Liquidado', 'Liquidado')], max_length=99999999, null=True)),
                ('clienteid', models.IntegerField(blank=True, null=True)),
                ('a_cuenta', models.IntegerField(blank=True, null=True)),
                ('deve', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('pago_con', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=99999999)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(default='system', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes_cosmeticos', to='Store.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=999999)),
                ('direccion', models.CharField(max_length=999999)),
                ('telefono', models.CharField(blank=True, max_length=9999, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventario_global',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo_id', models.CharField(max_length=99999999, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Articulos/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='BarCode/')),
                ('nombre', models.CharField(max_length=99999999)),
                ('detalles', models.CharField(blank=True, max_length=99999999, null=True)),
                ('contenido_pzas', models.CharField(blank=True, max_length=99999999)),
                ('precio_compra', models.CharField(blank=True, max_length=99999999)),
                ('precio_distribucion', models.CharField(blank=True, max_length=99999999, null=True)),
                ('precio_venta', models.IntegerField(blank=True, null=True)),
                ('inventario', models.IntegerField(blank=True, null=True)),
                ('inversion', models.CharField(blank=True, max_length=99999999)),
                ('monto_total', models.CharField(blank=True, max_length=99999999)),
                ('unidades_vendidas', models.CharField(blank=True, max_length=99999999, null=True)),
                ('numero_caja', models.CharField(blank=True, max_length=99999999, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventario_store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo_id', models.CharField(max_length=99999999, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Articulos/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='BarCode/')),
                ('nombre', models.CharField(max_length=99999999)),
                ('detalles', models.CharField(blank=True, max_length=99999999, null=True)),
                ('contenido_pzas', models.CharField(blank=True, max_length=99999999)),
                ('precio_venta', models.IntegerField(blank=True, null=True)),
                ('inventario', models.IntegerField(blank=True, null=True)),
                ('unidades_vendidas', models.CharField(blank=True, max_length=99999999, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=99999999, null=True)),
                ('articulo_id', models.CharField(blank=True, max_length=99999999, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=999999999)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('id_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.control_venta')),
            ],
        ),
        migrations.AddField(
            model_name='control_almacen',
            name='a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Store.empleado'),
        ),
    ]
