# Generated by Django 2.1.1 on 2020-05-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20200517_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liquidaciones_de_venta',
        ),
        migrations.RemoveField(
            model_name='control_venta',
            name='liquidacion_id',
        ),
    ]
