# Generated by Django 2.1.1 on 2020-05-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20200517_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='liquidaciondes_de_venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=999999, null=True)),
                ('liquido', models.IntegerField(blank=True, null=True)),
                ('monto_a_liquidar', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='control_venta',
            name='liquidacion_id',
            field=models.CharField(blank=True, max_length=99999999, null=True),
        ),
    ]
