# Generated by Django 2.1.1 on 2020-05-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20200517_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_store',
            name='unidades_vendidas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
