# Generated by Django 2.1.1 on 2020-05-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20200517_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='liquidaciondes_de_venta',
            new_name='liquidaciones_de_venta',
        ),
    ]
