# Generated by Django 2.1.1 on 2019-11-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_distribucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo_id', models.CharField(blank=True, max_length=99999999, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Articulos/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='BarCode/')),
                ('nombre', models.CharField(max_length=99999999)),
                ('detalles', models.CharField(blank=True, max_length=99999999, null=True)),
                ('contenido_pzas', models.CharField(blank=True, max_length=99999999)),
                ('precio_dist', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.IntegerField(blank=True, null=True)),
                ('inventario', models.IntegerField(blank=True, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Store.empleado')),
            ],
        ),
    ]
