# Generated by Django 2.1.1 on 2019-11-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_distribucion',
            name='nombre',
            field=models.CharField(max_length=99999999, unique=True),
        ),
    ]
