# Generated by Django 2.1.1 on 2019-11-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
        ('distribucion', '0002_auto_20191113_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_agregar_inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=99999999)),
                ('articulo_id', models.CharField(blank=True, max_length=99999999, null=True, unique=True)),
                ('nombre', models.CharField(max_length=99999999, unique=True)),
                ('inventario_antes', models.IntegerField(blank=True, null=True)),
                ('se_agregaron', models.IntegerField(blank=True, null=True)),
                ('inventario_despues', models.IntegerField(blank=True, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Store.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='control_venta_distribucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_cuenta', models.IntegerField(blank=True, null=True)),
                ('deve', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('pago_con', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=99999999)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Store.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='venta_distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=99999999, null=True)),
                ('articulo_id', models.CharField(blank=True, max_length=99999999, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=999999999)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('id_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribucion.control_venta_distribucion')),
            ],
        ),
    ]
