# Generated by Django 2.1.1 on 2019-11-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
        ('distribucion', '0005_auto_20191114_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_devolucion_inventario_dist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=99999999)),
                ('articulo_id', models.CharField(blank=True, max_length=99999999, null=True, unique=True)),
                ('nombre', models.CharField(max_length=99999999)),
                ('inventario_antes', models.IntegerField(blank=True, null=True)),
                ('se_agregaron', models.IntegerField(blank=True, null=True)),
                ('inventario_despues', models.IntegerField(blank=True, null=True)),
                ('registrado', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Store.empleado')),
            ],
        ),
        migrations.RenameModel(
            old_name='control_agregar_inventario',
            new_name='control_agregar_inventario_dist',
        ),
    ]
